### ISSUE TITLE
Problem with the header width

### ISSUE THREAD

**Issue by santigarcor** [DataTables/FixedColumns#35]
Everything in my table is alright but the FixedColumns part, the header width doesn't fit with the table content for example:

ID..........| ABC | Description |
1561653 |  A.. | Some text.....|
1561653 |  A.. | Some text.....|
1561653 |  A.. | Some text.....|
1561653 |  A.. | Some text.....|

i have tried recalculating the width but didn't work

**Comment by DataTables** [comment]
Please link to a test case showing the issue so it can be debugged.

**Comment by santigarcor** [comment]
i have solved it.
The problem were theselines in the datatables.bootstrap.css:

```css
table.dataTable td,
table.dataTable th {
	-webkit-box-sizing: content-box;
	-moz-box-sizing: content-box;
	box-sizing: content-box;
}
```

but when i removed that block it solved the problem in the normal datatable, but in the fixed columns happened the thing i posted before, so i added these lines in the css:

```css
div.DTFC_LeftWrapper table.dataTable,
div.DTFC_LeftWrapper table.dataTable td,
div.DTFC_LeftWrapper table.dataTable th {
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
```

and with that lines i solved the whole problem
